#!/usr/bin/env bash
# This file comes from https://github.com/xima-media/ddev-playwright
#
## Description: Run playwright command
## Usage: playwright [options] [command]
## Example: "ddev playwright test"
cd /var/www/html || exit 1
cd "${PLAYWRIGHT_TEST_DIR}" || exit 1

export PLAYWRIGHT_BROWSERS_PATH=0
export NODE_PATH=/deps/node_modules

if [[ "$1" == "show-report" ]]; then
  echo "Playwright report is available at: https://${VIRTUAL_HOST}:9323"

  playwright show-report --host=0.0.0.0 Tests/Playwright/playwright-report
fi

playwright "$@"
